### ISSUE TITLE
No switch metrics from docker deploy

### ISSUE THREAD

**Issue by jacqueslorentz** [dalance/prosafe_exporter#114]
Hello,

I have an issue, I have no metrics concerning the switch.

I deployed the exporter inside a docker container, with the following configuration:

prosafe_exporter version from commit b3747c26b8be20dd1cdcc2dfb4db2e68459ba3b3 from master

docker-compose.yml:
```yaml
[...]
  prosafe-exporter:
    build: ./prosafe_exporter
    container_name: prosafe-exporter
    restart: unless-stopped
    expose:
      - 9493
    networks:
      - monitoring
    command:
      - '--verbose'
[...]
```
prometheus.yml:
```yaml
[...]
- job_name: "prosafe"
    static_configs:
      - targets: ["192.168.1.8:*"]
    metrics_path: /probe
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: "prosafe-exporter:9493"
[...]
```
Switch product name: GS108Ev3
Switch bootloader version: V2.06.03
Switch firmware version: V2.06.14EN
Switch Management Mode: Configured on "Web browser and Plus Utility"

I can ping the switch from inside the conatiner with `sudo docker exec prosafe-exporter ping 192.168.1.8`

But with `sudo docker exec prosafe-exporter wget -O - localhost:9493/probe` I have only the following metrics:
```
# HELP prosafe_build_info A metric with a constant '1' value labeled by version, revision and rustversion.
# TYPE prosafe_build_info gauge
prosafe_build_info{revision="",rustversion="1.63.0",version="0.2.9-pre"} 1
```
Logs from container:
```
Server started: 0.0.0.0:9493
```

Did I missed something? Maybe there are an issue with docker networking?

Thanks a lot for your work!
